group: build
steps:
  - label: ":tapioca: build: ray py{{matrix}} docker (x86_64)"
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - if [[ "${NIGHTLY}"" == "1" ]]; then export NIGHTLY_ALIAS=true; else export NIGHTLY_ALIAS=false; fi
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu11.5.2 --platform cu11.6.2 --platform cu11.7.1
        --platform cu11.8.0 --platform cu12.1.1 --platform cpu
        --image-type ray
        --upload
        --nightly-alias ${NIGHTLY_ALIAS}
    depends_on:
      - manylinux
      - forge
      - raycudabase
      - raycpubase
    matrix:
      - "3.9"
