group: build
steps:
  - label: ":tapioca: build: ray py{{matrix}} docker (x86_64)"
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu11.5.2 --platform cu11.6.2 --platform cu11.7.1
        --platform cu11.8.0 --platform cu12.1.1 --platform cpu
        --image-type ray
        --upload
        --nightly-alias "${NIGHTLY_ALIAS}"
    depends_on:
      - manylinux
      - forge
      - raycudabase
      - raycpubase
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"

  - label: ":tapioca: build: ray py{{matrix}} docker (aarch64)"
    tags:
      - python_dependencies
      - docker
      - core_cpp
      - oss
    instance_type: medium-arm64
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu11.5.2 --platform cu11.6.2 --platform cu11.7.1
        --platform cu11.8.0 --platform cu12.1.1 --platform cpu
        --image-type ray
        --architecture aarch64
        --upload
        --nightly-alias "${NIGHTLY_ALIAS}"
    depends_on:
      - manylinux-aarch64
      - forge-aarch64
      - raycudabase-aarch64
      - raycpubase-aarch64
    job_env: forge-aarch64
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"

  - label: ":tapioca: build: ray-ml py{{matrix}} docker (x86_64)"
    tags:
      - python_dependencies
      - docker
      - oss
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- docker --python-version {{matrix}}
        --platform cu11.8.0 --platform cpu --image-type ray-ml
        --upload
        --nightly-alias "${NIGHTLY_ALIAS}"
    depends_on:
      - manylinux
      - forge
      - ray-mlcudabase
      - ray-mlcpubase
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"